---

- name: Intall DVWA Playbook
  hosts: webservers
  become: true
  tasks:

  - name: Update apt
    apt:
      update_cache: yes

  - name: Remove apache
    apt:
      name: apache2
      state: absent

  - name: Install docker.io
    apt:
      name: docker.io
      state: present

  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present

  - name: Install docker python package
    pip:
      name: docker
      state: present

  - name: Install cyberxsecurity/dvwa container
    community.docker.docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      published_ports: 80:80
      state: started
      restart_policy: always

  - name: Configure systemd to start docker when VM starts
    systemd:
      name: docker.service
      state: started